travis:
  secure:
    BINSTAR_TOKEN: OaTKQfRjnPSTX6uJ0j6BPv0ZREstoyTBi2y3+x9ShDRaz/u86G2h0ekvBRHdKwLM9txS+G5e75VujbDL6JtE5FNZdxRKiZDlK+7yAOvAksUlFznCZGqhREBXC6BthUruY4ai9aEFWgpJKWYdnCURi5pTPTSEb9vAnVLAq1Hg8dABGnJo/Dc3wobNBgJ1T3GXCzpcSgy22CK3u6U3Urb92b3P9wSf2b4UwAr0jCu+ME2HGe01SHvjycttv/CeSBM3bryMh0DqNfjOoxBFU+D0QUE1LkjVz1c9sID2WYDznPm6mTy89XZfSu+aYCG7xF5feakyBvkbFDqfGHO8RU2tYWhJhFahzZ0CERnLkvKt/ae2uVMBsXebd7Zz6D59M38KFbGNHsYZ/p3Fc4/FdNZ0MPbYwT+IRyja1KwDwOcqI7U/nBRS13zDqTsUxaKVowd1HcEwmnolfpiKdUuS7Nng9qZRFLLt1e4ncjifNaAAxQZHKlFHbQPtz3CMqerXVH+ew3+8B4CXp50r6p0xjDg4zPkDWog9JmjU69uUrg8uF3N1XEC84Ay1ww4Dt9qlGGj3jdPVmOOPOPpinSdBV9PteEb6Y/uOAKSpEMLvYa3ywKxhXA/kxNoob3uUc85H4gTCi/e39aBXJw/xDLF+LFCDjSh4QAaHhBFqQlVEOlXsGt8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
